#!/bin/bash
#
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#
# Only edit the template files, then run
#   cmsh -c "device initialize <switch-hostname>"
#

function error() {
  echo -e "\e[0;33mERROR: Provisioning error running $BASH_COMMAND at line $BASH_LINENO of $(basename $0) \e[0m" >&2
}

# Log all output from this script
exec >/var/log/autoprovision 2>&1

trap error ERR

echo "[ztp:start]"

for target in "/root" "/home/cumulus"; do
  if [ ! -e "$target/.alias" ]; then
    echo "alias ll='ls -alhF --color'" > "$target/.alias"
  fi
done

# TODO: add fixed code here

echo "[start:cmd]"
# This section of this file was automatically generated by cmd. Do not edit manually!
# BEGIN AUTOGENERATED SECTION -- DO NOT REMOVE
# END AUTOGENERATED SECTION   -- DO NOT REMOVE
echo "[end:cmd]"

#
# BCM10 vs BCM11 compatibility notes:
# - BCM11 typically sets CM_LITE_DAEMON="YES" (BCM10 often uses "yes").
# - BCM11 adds Ubuntu 24 (debian_version 13) repo/auth variables.
# - BCM11 may gate whether NVUE config is applied during ZTP via CMD_APPLY_NV_FROM_ZTP.
# - BCM11 may gate /etc/hosts updates via CMD_UPDATE_ETC_HOSTS and uses CMD_HEAD_NODE_SHARED_IP.
#
cm_bool_is_yes() {
  # Usage: cm_bool_is_yes "$value"
  case "${1:-}" in
    YES|Yes|yes|Y|y|true|True|TRUE|1) return 0 ;;
    *) return 1 ;;
  esac
}

cmd_vrf_exec() {
  # Run a command in CMD_VRF if configured AND the VRF device exists; otherwise run normally.
  # This mirrors BCM11's general "try multiple reachability methods" approach without breaking BCM10.
  if [ -n "${CMD_VRF:-}" ] && ip link show dev "${CMD_VRF}" >/dev/null 2>&1; then
    ip vrf exec "${CMD_VRF}" "$@"
  else
    "$@"
  fi
}

echo "[start:pre]"
if [ ! -z "$CMD_PRE_SCRIPTS" ]; then
  echo "* count: $CMD_PRE_SCRIPTS"
  for i in $(seq 1 $CMD_PRE_SCRIPTS); do
    name="CMD_PRE_SCRIPTS_$i"
    echo "* run: ${!name}"
    cmd_vrf_exec wget --no-check-certificate -O "/var/run/cmd-pre-script" "${!name}"
    source "/var/run/cmd-pre-script"
  done
  rm -f "/var/run/cmd-pre-script"
fi
echo "[end:pre]"

continue_ztp=1
echo "[start:image]"
CURRENT_RELEASE=$(cat /etc/lsb-release | grep RELEASE | cut -d "=" -f2)
if [ "$CMD_CHECK_IMAGE" != "YES" ]; then
  echo "* not checking image version"
else
  if [ -z "$CMD_IMAGE_URL" ]; then
    echo "* image url not specified"
  else
    if [ -z "$CMD_TARGET_RELEASE" ]; then
      echo "* no target release"
    else
      if [ -z "$CURRENT_RELEASE" ]; then
        echo "* no curent release"
      else
        echo "* current: $CURRENT_RELEASE"
        echo "* target:  $CMD_TARGET_RELEASE"
        if [ "$CMD_TARGET_RELEASE" != "$CURRENT_RELEASE" ]; then
          continue_ztp=0
          echo "* run onie-install"
          echo "  - image:   $CMD_IMAGE_URL"
          echo "  - ztp:     $CMD_ZTP_URL"
          /usr/cumulus/bin/onie-install -fa -i "$CMD_IMAGE_URL" -z "$CMD_ZTP_URL" && reboot
        fi
      fi
    fi
  fi
fi
echo "[end:image]"

if [ $continue_ztp -gt 0 ]; then
  mkdir -p "/cm/local/apps/etc"
  cd "/cm/local/apps/"

  echo "[begin:nv]"
  if [ -z "$CMD_NV_CONFIG" ]; then
    echo "* no nv config supplied"
  else
    cd "etc"
    basename=$(basename -- "$CMD_NV_CONFIG")
    update_nv=0
    if [ -e "$basename" ]; then
      extension=${basename##*.}
      filename=${basename%.*}
      cmd_vrf_exec wget --no-check-certificate -O "$filename-latest.$extension" "$CMD_NV_CONFIG"
      if ! diff "$filename-latest.$extension" "$basename"; then
        echo "* nv config changed"
        mv "$filename-latest.$extension" "$basename"
        update_nv=1
      else
        echo "* nv config unchanged"
        rm "$filename-latest.$extension"
      fi
    else
      echo "* first time nv config was supplied"
      cmd_vrf_exec wget --no-check-certificate -O "$basename" "$CMD_NV_CONFIG"
      update_nv=1
    fi
    if [ $update_nv -gt 0 ]; then
      # BCM11 can gate NVUE apply from ZTP (CMD_APPLY_NV_FROM_ZTP=YES).
      # Default to applying for backward compatibility if variable is unset.
      if [ -z "${CMD_APPLY_NV_FROM_ZTP:-}" ] || cm_bool_is_yes "${CMD_APPLY_NV_FROM_ZTP:-}"; then
        echo "* replace nv config"
        nv config replace "$basename"
        echo "* apply nv config"
        nv config apply -y
        echo "* save nv config to /etc/nvue.d/startup.yaml"
        nv config save
      else
        echo "* CMD_APPLY_NV_FROM_ZTP != YES; downloaded config but will not apply via ZTP"
        # BCM11 uses this marker to indicate NV should be applied later by cm-lite-daemon.
        echo "ZTP" > /var/run/cm-lite-daemon.apply
      fi
    fi
    cd ..
  fi
  echo "[end:nv]"

  # BCM11 can gate /etc/hosts updates and prefers the shared head-node IP when provided.
  if [ -z "${CMD_UPDATE_ETC_HOSTS:-}" ] || cm_bool_is_yes "${CMD_UPDATE_ETC_HOSTS:-}"; then
    hosts_ip="${CMD_HEAD_NODE_SHARED_IP:-${CMD_HEAD_NODE_IP:-}}"
    if [ -n "$hosts_ip" ]; then
      if grep -q "master" /etc/hosts; then
        echo "* update head node IP in /etc/hosts: $hosts_ip"
        perl -pi.ztp -e 's/(#?).*master.*/${1}'$hosts_ip'    master.cm.cluster master/g' /etc/hosts
      else
        echo "* add head node IP to /etc/hosts: $hosts_ip"
        echo "$hosts_ip    master.cm.cluster master" >> /etc/hosts
      fi
    fi
  else
    echo "* CMD_UPDATE_ETC_HOSTS != YES; skipping /etc/hosts update"
  fi

  if [ ! -z "$CMD_ROOT_SSH_AUTHORIZED_KEYS" ]; then
    mkdir -p /root/.ssh
    cmd_vrf_exec wget --no-check-certificate -O /root/.ssh/authorized_keys "$CMD_ROOT_SSH_AUTHORIZED_KEYS"
  fi
  if [ ! -z "$CMD_CUMULUS_SSH_AUTHORIZED_KEYS" ]; then
    mkdir -p /home/cumulus/.ssh
    cmd_vrf_exec wget --no-check-certificate -O /home/cumulus/.ssh/authorized_keys "$CMD_CUMULUS_SSH_AUTHORIZED_KEYS"
    chown -R cumulus:cumulus /home/cumulus/.ssh
  fi

  repo=
  DEB_VERSION=$(cat /etc/debian_version | cut -d. -f1)
  if [ "$DEB_VERSION" = "10" ]; then
    echo "* detected ubuntu 18 variant"
    repo=$CMD_CM_REPO_U18
    auth=$CMD_CM_AUTH_U18
  elif [ "$DEB_VERSION" = "11" ]; then
    echo "* detected ubuntu 20 variant"
    repo=$CMD_CM_REPO_U20
    auth=$CMD_CM_AUTH_U20
  elif [ "$DEB_VERSION" = "12" ]; then
    echo "* detected ubuntu 22 variant"
    repo=$CMD_CM_REPO_U22
    auth=$CMD_CM_AUTH_U22
  elif [ "$DEB_VERSION" = "13" ]; then
    echo "* detected ubuntu 24 variant"
    repo=$CMD_CM_REPO_U24
    auth=$CMD_CM_AUTH_U24
  else
    echo "!!! unknown OS !!!"
  fi

  if [ -z "$repo" ]; then
    if cm_bool_is_yes "${CM_LITE_DAEMON:-}"; then
      echo "!!! unable to determine repository to get cm-lite-daemon from !!!"
    fi
  elif cm_bool_is_yes "${CM_LITE_DAEMON:-}"; then
    echo "[start:cm-lite-daemon]"
    echo "* deferring cm-lite-daemon install/registration (will retry until eth0/VRF can reach BCM)"

    # Persist all CMD_* values we need for the deferred bootstrap in an env file.
    # (systemd units won't inherit this script environment.)
    mkdir -p /etc/cmd
    {
      printf "CMD_HOSTNAME=%q\n" "${CMD_HOSTNAME:-}"
      printf "CMD_NODE_NAME=%q\n" "${CMD_NODE_NAME:-}"
      printf "CMD_VRF=%q\n" "${CMD_VRF:-}"
      printf "CMD_INTERFACE=%q\n" "${CMD_INTERFACE:-}"
      printf "CMD_HEAD_NODE_IP=%q\n" "${CMD_HEAD_NODE_IP:-}"
      printf "CMD_HEAD_NODE_SHARED_IP=%q\n" "${CMD_HEAD_NODE_SHARED_IP:-}"
      printf "CMD_UPDATE_ETC_HOSTS=%q\n" "${CMD_UPDATE_ETC_HOSTS:-}"
      printf "CMD_APPLY_NV_FROM_ZTP=%q\n" "${CMD_APPLY_NV_FROM_ZTP:-}"
      printf "CMD_DOMAIN_NAME=%q\n" "${CMD_DOMAIN_NAME:-}"
      printf "CMD_GLOBAL_DOMAIN_NAME=%q\n" "${CMD_GLOBAL_DOMAIN_NAME:-}"
      printf "CMD_BASE_URL=%q\n" "${CMD_BASE_URL:-}"
      printf "CMD_HEALTH_CHECKS=%q\n" "${CMD_HEALTH_CHECKS:-}"
      printf "CMD_CLUSTER_PEM=%q\n" "${CMD_CLUSTER_PEM:-}"
      printf "CMD_BOOTSTRAP_PEM=%q\n" "${CMD_BOOTSTRAP_PEM:-}"
      printf "CMD_BOOTSTRAP_KEY=%q\n" "${CMD_BOOTSTRAP_KEY:-}"
      printf "CMD_CM_GPG=%q\n" "${CMD_CM_GPG:-}"
      printf "CMD_CM_NIGHTLY_CONF=%q\n" "${CMD_CM_NIGHTLY_CONF:-}"
      printf "CMD_CM_REPO_U18=%q\n" "${CMD_CM_REPO_U18:-}"
      printf "CMD_CM_AUTH_U18=%q\n" "${CMD_CM_AUTH_U18:-}"
      printf "CMD_CM_REPO_U20=%q\n" "${CMD_CM_REPO_U20:-}"
      printf "CMD_CM_AUTH_U20=%q\n" "${CMD_CM_AUTH_U20:-}"
      printf "CMD_CM_REPO_U22=%q\n" "${CMD_CM_REPO_U22:-}"
      printf "CMD_CM_AUTH_U22=%q\n" "${CMD_CM_AUTH_U22:-}"
      printf "CMD_CM_REPO_U24=%q\n" "${CMD_CM_REPO_U24:-}"
      printf "CMD_CM_AUTH_U24=%q\n" "${CMD_CM_AUTH_U24:-}"
    } > /etc/cmd/cm-lite-bootstrap.env

    cat > /usr/local/sbin/cmd-cm-lite-bootstrap.sh <<'EOF'
#!/bin/bash
set -euo pipefail

log="/var/log/cmd-cm-lite-bootstrap.log"
exec >>"$log" 2>&1

echo "[cmd-cm-lite-bootstrap:start] $(date -Is)"

set -a
source /etc/cmd/cm-lite-bootstrap.env
set +a

vrf="${CMD_VRF:-mgmt}"
interface="${CMD_INTERFACE:-eth0}"

head_node="master"
if [ -n "${CMD_GLOBAL_DOMAIN_NAME:-}" ]; then
  head_node="$head_node.$CMD_GLOBAL_DOMAIN_NAME"
elif [ -n "${CMD_DOMAIN_NAME:-}" ]; then
  head_node="$head_node.$CMD_DOMAIN_NAME"
fi

reach_target="${CMD_HEAD_NODE_IP:-$head_node}"
host_arg="${CMD_HEAD_NODE_IP:-$head_node}"

vrf_exec() {
  ip vrf exec "$vrf" "$@"
}

if [ -e "/cm/local/apps/cm-lite-daemon/etc/cert.pem" ]; then
  echo "* cert.pem exists; attempt to ensure cm-lite-daemon is runnable"
  # Don't disable the retry timer until the daemon is actually active.
  systemctl enable --now cm-lite-daemon 2>/dev/null || true
  systemctl restart cm-lite-daemon 2>/dev/null || true
  if systemctl is-active --quiet cm-lite-daemon; then
    echo "* cm-lite-daemon active; disabling retry timer"
    systemctl disable --now cmd-cm-lite-bootstrap.timer || true
    exit 0
  fi
  echo "* cm-lite-daemon not active yet; will retry"
  exit 1
fi

if ! ip link show dev "$interface" >/dev/null 2>&1; then
  echo "* interface $interface does not exist yet; will retry"
  exit 1
fi

if ! ip -4 addr show dev "$interface" | grep -q "inet "; then
  echo "* interface $interface has no IPv4 yet; will retry"
  exit 1
fi

if ! vrf_exec ping -c1 -W1 "$reach_target" >/dev/null 2>&1; then
  echo "* cannot reach $reach_target in VRF $vrf yet; will retry"
  exit 1
fi

DEB_VERSION=$(cat /etc/debian_version | cut -d. -f1)
repo=""
auth=""
if [ "$DEB_VERSION" = "10" ]; then
  repo="${CMD_CM_REPO_U18:-}"
  auth="${CMD_CM_AUTH_U18:-}"
elif [ "$DEB_VERSION" = "11" ]; then
  repo="${CMD_CM_REPO_U20:-}"
  auth="${CMD_CM_AUTH_U20:-}"
elif [ "$DEB_VERSION" = "12" ]; then
  repo="${CMD_CM_REPO_U22:-}"
  auth="${CMD_CM_AUTH_U22:-}"
elif [ "$DEB_VERSION" = "13" ]; then
  repo="${CMD_CM_REPO_U24:-}"
  auth="${CMD_CM_AUTH_U24:-}"
else
  echo "!!! unknown OS !!! debian_version=$DEB_VERSION"
  exit 1
fi

if [ -z "$repo" ]; then
  echo "!!! repository not specified; cannot install cm-lite-daemon !!!"
  exit 1
fi

target="/etc/apt/sources.list.d/cm.list"
if [ ! -e "$target.freeze" ]; then
  vrf_exec wget --no-check-certificate -O "$target" "$repo"
fi

if [ -n "${CMD_CM_GPG:-}" ]; then
  target="/etc/apt/trusted.gpg.d/brightcomputing-archive-cm.gpg"
  if [ ! -e "$target.freeze" ]; then
    vrf_exec wget --no-check-certificate -O "$target" "$CMD_CM_GPG"
  fi
fi

if [ -n "${CMD_CM_NIGHTLY_CONF:-}" ]; then
  target="/etc/apt/auth.conf.d/cm-nightly.conf"
  if [ ! -e "$target.freeze" ]; then
    vrf_exec wget --no-check-certificate -O "$target" "$CMD_CM_NIGHTLY_CONF"
    if [ "$DEB_VERSION" = "10" ]; then
      perl -pi -e 's#http://##g' "$target"
    fi
  fi
elif [ -n "$auth" ]; then
  target="/etc/apt/auth.conf.d/cm.conf"
  if [ ! -e "$target.freeze" ]; then
    vrf_exec wget --no-check-certificate -O "$target" "$auth"
  fi
fi

echo "[start:apt-get]"
vrf_exec apt-get update -y
# BCM11 template installs only cm-python3 + cm-lite-daemon. Some BCM10 repos also provide cm-python39.
# Try the superset first, then fall back without cm-python39 for compatibility.
if ! vrf_exec apt-get install -y cm-python3 cm-python39 cm-lite-daemon; then
  vrf_exec apt-get install -y cm-python3 cm-lite-daemon
fi
echo "[end:apt-get]"

echo "[start:cm-lite-daemon]"
fix_cmlite_systemd() {
  # If the packaged systemd unit still contains 'RUN_ENV@', force a valid ExecStart via a systemd drop-in.
  # (We prefer a drop-in rather than editing packaged unit files.)
  needs_fix=0
  for unit in /lib/systemd/system/cm-lite-daemon.service /usr/lib/systemd/system/cm-lite-daemon.service; do
    if [ -e "$unit" ] && grep -q 'RUN_ENV@' "$unit"; then
      needs_fix=1
    fi
  done

  if [ "$needs_fix" -gt 0 ]; then
    # NOTE: A drop-in is NOT sufficient here: systemd treats the '@RUN_ENV@...' ExecStart as a fatal
    # parse error and refuses to load the unit at all (Loaded: bad-setting). In that case, it won't
    # apply drop-ins. So we write a full override unit in /etc (higher priority than /lib).
    echo "* detected templated cm-lite-daemon unit (RUN_ENV@); writing full override unit in /etc/systemd/system"
    cat > /etc/systemd/system/cm-lite-daemon.service <<EOF2
[Unit]
Description=Bright Computing Cluster Lite Manager daemon
After=syslog.service network-online.target networking.service time-sync.target

[Service]
Type=simple
Restart=on-failure
RestartSec=5
StartLimitInterval=1m
StartLimitBurst=3
EnvironmentFile=/cm/local/apps/cm-lite-daemon/etc/cm-lite-daemon.env
ExecStart=/usr/sbin/ip vrf exec $vrf /cm/local/apps/cm-lite-daemon/cm-lite-daemon --daemon --pid-file "/var/run/cm-lite-daemon.pid"
ExecStop=/cm/local/apps/cm-lite-daemon/cm-lite-daemon_ctl stop
TimeoutStopSec=45
TasksMax=128
MemoryHigh=488M
MemoryMax=512M

[Install]
WantedBy=multi-user.target
EOF2
    systemctl daemon-reload
    echo "* installed override unit: /etc/systemd/system/cm-lite-daemon.service"
    systemctl cat cm-lite-daemon | sed -n '1,80p' || true
  fi
}

# Try to install the drop-in as soon as cm-lite-daemon is installed (even before register_node),
# so we don't depend on register_node successfully rendering a packaged unit.
fix_cmlite_systemd

healthchecks_directory="/cm/local/apps/cmd/scripts/healthchecks"
mkdir -p "$healthchecks_directory"
if [ -n "${CMD_HEALTH_CHECKS:-}" ]; then
  for name in $CMD_HEALTH_CHECKS; do
    echo "* get health check: $name"
    vrf_exec wget --no-check-certificate -O "$healthchecks_directory/$name" "$CMD_BASE_URL/$name"
    chmod u+x "$healthchecks_directory/$name"
  done
fi

cd "/cm/local/apps/cm-lite-daemon"
if [ -e "etc/cluster.pem" ]; then
  vrf_exec wget --no-check-certificate -O /tmp/cluster.pem "$CMD_CLUSTER_PEM"
  if diff /tmp/cluster.pem etc/cluster.pem > /dev/null; then
    echo "* keep cluster certificate"
    rm -f /tmp/cluster.pem
  else
    echo "* update cluster certificate"
    mv /tmp/cluster.pem etc/cluster.pem
    rm -f etc/bootstrap.pem
    rm -f etc/bootstrap.key
    rm -f etc/cert.pem
    rm -f etc/cert.key
  fi
else
  echo "* get cluster certificate"
  vrf_exec wget --no-check-certificate -O etc/cluster.pem "$CMD_CLUSTER_PEM"
fi

if [ -e "etc/cert.pem" ]; then
  echo "* cm-lite-daemon already setup"
  fix_cmlite_systemd
else
  echo "* setup cm-lite-daemon for the first time"
  echo "* get bootstrap certificate"
  vrf_exec wget --no-check-certificate -O etc/bootstrap.pem "$CMD_BOOTSTRAP_PEM"
  vrf_exec wget --no-check-certificate -O etc/bootstrap.key "$CMD_BOOTSTRAP_KEY"

  # Some builds ship only cm-lite-daemon.env (no .env.in). register_node expects the .env.in template.
  if [ ! -e "/cm/local/apps/cm-lite-daemon/etc/cm-lite-daemon.env.in" ] && [ -e "/cm/local/apps/cm-lite-daemon/etc/cm-lite-daemon.env" ]; then
    cp -n "/cm/local/apps/cm-lite-daemon/etc/cm-lite-daemon.env" "/cm/local/apps/cm-lite-daemon/etc/cm-lite-daemon.env.in" || true
  fi

  # Prefer using the switch's runtime hostname as the node identity. This avoids issues in BCM10
  # workarounds where ZTP was delivered via a "bootstrap" device record (MAC-based), but the
  # switch should ultimately register as its real hostname after NVUE config applies.
  node_name="${CMD_NODE_NAME:-$(hostname -s 2>/dev/null || hostname)}"

  echo "* register cm-lite-daemon node=$node_name host=$host_arg vrf=$vrf interface=$interface"
  vrf_exec ./register_node --node "$node_name" \
                  --interface "$interface" \
                  --vrf "$vrf" \
                  --host "$host_arg" \
                  --disable-cert-check \
                  --disable-hostname-check

  fix_cmlite_systemd
  cd ..
fi

# Try to start cm-lite-daemon now that we may have fixed the systemd unit.
systemctl enable --now cm-lite-daemon 2>/dev/null || true
systemctl restart cm-lite-daemon 2>/dev/null || true
service cm-lite-daemon status || true
echo "[end:cm-lite-daemon]"

if [ -e "/cm/local/apps/cm-lite-daemon/etc/cert.pem" ]; then
  echo "* completed; disabling retry timer"
  systemctl disable --now cmd-cm-lite-bootstrap.timer || true
fi

echo "[cmd-cm-lite-bootstrap:end] $(date -Is)"
EOF

    chmod 0755 /usr/local/sbin/cmd-cm-lite-bootstrap.sh

    cat > /etc/systemd/system/cmd-cm-lite-bootstrap.service <<'EOF'
[Unit]
Description=Deferred cm-lite-daemon install/registration (retry until ready)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/cmd-cm-lite-bootstrap.sh
EOF

    cat > /etc/systemd/system/cmd-cm-lite-bootstrap.timer <<'EOF'
[Unit]
Description=Retry deferred cm-lite-daemon install/registration

[Timer]
OnBootSec=30
OnUnitInactiveSec=60
AccuracySec=10

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now cmd-cm-lite-bootstrap.timer
    echo "* enabled cmd-cm-lite-bootstrap.timer (will keep retrying)"
    echo "[end:cm-lite-daemon]"
    cd /root
  fi

  if [ ! -z "$CMD_PTM_TOPOLOGY" ]; then
    echo "[start:ptm]"
    restart_ptmd=0
    mkdir -p /etc/ptm.d
    if [ -e "/etc/ptm.d/topology.dot" ]; then
      wget --no-check-certificate -O /tmp/topology.dot "$CMD_PTM_TOPOLOGY"
      if diff /tmp/topology.dot /etc/ptm.d/topology.dot > /dev/null; then
        echo "* keep ptm topology"
        rm /tmp/topology.dot
        if ! systemctl status ptmd.service > /dev/null; then
          restart_ptmd=1
        fi
      else
        echo "* update ptm topology"
        mv /tmp/topology.dot /etc/ptm.d/topology.dot
        restart_ptmd=1
      fi
    else
      echo "* add ptm topology"
      wget --no-check-certificate -O /etc/ptm.d/topology.dot "$CMD_PTM_TOPOLOGY"
      restart_ptmd=1
    fi
    if [ $restart_ptmd -gt 0 ]; then
      echo "* restart ptmd"
      systemctl restart ptmd.service
    fi
    echo "[end:ptm]"
  fi

  nvue="/etc/nginx/sites-enabled/nvue.conf"
  if [ "$CMD_ENABLE_API" == "YES" ]; then
    restart_nginx=0

    echo "[start:nvue]"
    if [ ! -e "$nvue" ]; then
      echo "* create symlink"
      ln -s /etc/nginx/sites-{available,enabled}/nvue.conf
      restart_nginx=1
    fi

    if [ "$CMD_ENABLE_EXTERNAL_ACCESS_API" == "YES" ]; then
      if grep -q localhost:8765 "$nvue" ; then
        echo "* switch listen to 0.0.0.0"
        sed -i 's/listen localhost:8765 ssl;/listen 0.0.0.0:8765 ssl;/g' "$nvue"
        restart_nginx=1
      fi
    else
      if grep -q 0.0.0.0:8765 "$nvue" ; then
        echo "* switch listen to localhosst"
        sed -i 's/listen 0.0.0.0:8765 ssl;/listen localhost:8765 ssl;/g' "$nvue"
        restart_nginx=1
      fi
    fi
    echo "[end:nvue]"

    if [ $restart_nginx -gt 0 ]; then
      echo "[restart:nginx]"
      echo "* restart nginx"
      systemctl restart nginx.service
      echo "[start:nginx]"
    fi
  elif [ -e "$nvue" ]; then
    echo "[start:nvue]"
    echo "* remove symlink"
    rm -f "$nvue"
    echo "* stop nginx"
    systemctl stop nginx.service
    echo "[end:nvue]"
  fi
fi

if [[ ! -z "$CMD_ACCESS_USER" && "$CURRENT_RELEASE" =~ ^5\.[0-8]\. ]]; then
  echo "[start:password]"
  desired="99999"
  expire=$(passwd -S "$CMD_ACCESS_USER" | cut -d" " -f 5)
  if [ "$desired" != "$expire" -o "$CMD_ACCESS_UPDATE" = "yes" ]; then
    echo "* change expire from $expire to $desired"
    passwd -x "$desired" "$CMD_ACCESS_USER"
    if [ ! -z "$CMD_ACCESS_CRYPT_PASSWORD" ]; then
      echo "* change crypt password"
      usermod -p "$CMD_ACCESS_CRYPT_PASSWORD" "$CMD_ACCESS_USER"
    elif [ ! -z "$CMD_ACCESS_PASSWORD" ]; then
      echo "* change password"
      echo "$CMD_ACCESS_USER:$CMD_ACCESS_CRYPT_PASSWORD" | chpasswd
    else
      echo "* no password specified"
    fi
  fi
  echo "[end:password]"
fi

echo "[start:post]"
if [ ! -z "$CMD_POST_SCRIPTS" ]; then
  echo "* count: $CMD_POST_SCRIPTS"
  for i in $(seq 1 $CMD_POST_SCRIPTS); do
    name="CMD_POST_SCRIPTS_$i"
    echo "* run: ${!name}"
    wget --no-check-certificate -O "/var/run/cmd-post-script" "${!name}"
    source "/var/run/cmd-post-script"
  done
  rm -f "/var/run/cmd-post-script"
fi
echo "[end:post]"

echo "[ztp:end]"

#
# Do not remove the following line
# CUMULUS-AUTOPROVISIONING
#
exit 0
